### ISSUE TITLE
[ViewRaw] Timestamp is less accurate than extracted from snowflake

### ISSUE THREAD

**Issue by KaKi87** [Juby210/Aliucord-plugins#10]

**Comment by Juby210** [comment]
What do you mean by that? How is that less accurate? It is literally what discord stores in the memory.

**Comment by KaKi87** [comment]
For example, it will provide this :
```json
{
  "timestamp": {
    "dateTimeMillis": 1629060658000
  }
}
```
Aka this : `2021-08-15T20:50:58.000Z`
While the timestamp extracted from the snowflake ID will provide this : `2021-08-15T20:50:58.839Z`
The data from ViewRaw is less accurate than the data from the snowflake ID : milliseconds are lost.

**Comment by Juby210** [comment]
https://github.com/Juby210/Aliucord-plugins/blob/main/ViewRaw/src/main/java/com/aliucord/plugins/ViewRaw.java#L81
Then just discord does that not me.
