### ISSUE TITLE
More new Twemoji emojis for NewEmoji

### ISSUE THREAD

**Issue by 5h3i1ah** [Juby210/Aliucord-plugins#59]
The fork of Twemoji that Discord uses got an update, so Discord now officially supports yet more emojis. I would greatly appreciate if these were added to the NewEmojis plugin! https://github.com/jdecked/twemoji

**Comment by 5h3i1ah** [comment]
poke

**Comment by Juby210** [comment]
updated deee8d760241c2cdf1499f7e0f63953704093325
