### ISSUE TITLE
Suggestion for PronounDB

### ISSUE THREAD

**Issue by vy-storm** [Juby210/Aliucord-plugins#9]
Simple one, but it would be nice if one could make pronouns show up on the profile page as opposed to in chat, reason being it tends to cut off names really easily as of now.

An extension of this could be if pronouns showed in chat by default but you could toggle them off on a per user basis by tapping their pronouns in their profile, that way you can learn the pronouns of new people then hide them once you know them.  All that might be overkill tho

**Comment by Juby210** [comment]
Already does that, check plugin settings. ![Screenshot_20210810-133025.jpg](https://user-images.githubusercontent.com/31005896/128859759-7f4548e8-1d39-420e-a949-128ee3834106.jpg)

![Screenshot_20210810-133039.jpg](https://user-images.githubusercontent.com/31005896/128859771-80e01bb8-d0c2-486c-b91a-f2264a97b4b4.jpg)

**Comment by vy-storm** [comment]
> Already does that, check plugin settings. ![Screenshot_20210810-133025.jpg](https://user-images.githubusercontent.com/31005896/128859759-7f4548e8-1d39-420e-a949-128ee3834106.jpg)
> 
> ![Screenshot_20210810-133039.jpg](https://user-images.githubusercontent.com/31005896/128859771-80e01bb8-d0c2-486c-b91a-f2264a97b4b4.jpg)

Oh now I see it, I looked on the profile pages of people with pronouns before but couldn't find anything!  Why is it in such an obscure location?

**Comment by vy-storm** [comment]
> Already does that, check plugin settings. ![Screenshot_20210810-133025.jpg](https://user-images.githubusercontent.com/31005896/128859759-7f4548e8-1d39-420e-a949-128ee3834106.jpg)
> 
> ![Screenshot_20210810-133039.jpg](https://user-images.githubusercontent.com/31005896/128859771-80e01bb8-d0c2-486c-b91a-f2264a97b4b4.jpg)

Have you considered putting it next to the about me? So:

About Me • He/Him

Like this?  At the moment you can't even see it when you first open profiles.

**Comment by Juby210** [comment]
It is just how powercord's version does it.
